blank_issues_enabled: false
contact_links:
  - name: â“æå‡ºé—®é¢˜
    url: https://github.com/IvanHanloth/BossKey/discussions
    about: æé—®é¡¹ç›®ç›¸å…³çš„å…¶ä»–é—®é¢˜
  - name: ğŸ“„å®˜æ–¹æ–‡æ¡£
    url: https://ivanhanloth.github.io/Boss-Key/
    about: åœ¨åˆ›å»º Issue ä¹‹å‰ï¼Œè¯·ä»”ç»†æŸ¥é˜… Bili23 Downloader ä½¿ç”¨æ‰‹å†Œä»¥ç¡®ä¿æ­£ç¡®ä½¿ç”¨ã€‚